"""Generates every app icon from one drawing: the "calendar dial" (a
calendar page whose body is a clock face), white on the app's teal.

    python3 tool/icon/generate.py

Needs Pillow and Playwright's Chromium (`pip install pillow playwright`;
PLAYWRIGHT_BROWSERS_PATH or `playwright install chromium`). Writes:

- tool/icon/app_icon.svg, app_icon_monochrome.svg: the masters, for reference
- Android: the adaptive icon's foreground and monochrome (themed icon)
  vectors, and ic_launcher.png fallbacks for Android 7 and older
- web: favicon.png and the PWA icons, plain and maskable
- Windows: runner/resources/app_icon.ico

The drawing is on the 108x108 adaptive-icon canvas: launchers show the
middle 72x72 (18..90), and mask it to their icon shape.
"""

import io
import math
import os
import sys

from PIL import Image
from playwright.sync_api import sync_playwright

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TEAL = "#00695C"
WHITE = "#FFFFFF"
LIGHT_TEAL = "#80CBC4"


def rounded_rect(x, y, w, h, r):
    return (
        f"M{x + r},{y} H{x + w - r} A{r},{r} 0 0 1 {x + w},{y + r} "
        f"V{y + h - r} A{r},{r} 0 0 1 {x + w - r},{y + h} "
        f"H{x + r} A{r},{r} 0 0 1 {x},{y + h - r} "
        f"V{y + r} A{r},{r} 0 0 1 {x + r},{y} Z"
    )


def circle(cx, cy, r):
    return f"M{cx - r},{cy} A{r},{r} 0 1 0 {cx + r},{cy} A{r},{r} 0 1 0 {cx - r},{cy} Z"


def hand(cx, cy, clock_degrees, length):
    a = math.radians(clock_degrees - 90)
    return f"M{cx},{cy} L{cx + length * math.cos(a):.2f},{cy + length * math.sin(a):.2f}"


# The calendar page: body, header band (rounded top corners), two rings.
BODY = rounded_rect(27, 28, 54, 54, 10)
HEADER = "M27,43 V38 A10,10 0 0 1 37,28 H71 A10,10 0 0 1 81,38 V43 Z"
RINGS = rounded_rect(38, 22, 5, 13, 2.5) + " " + rounded_rect(65, 22, 5, 13, 2.5)
# The clock in its body, at 10:10.
DIAL = circle(54, 62, 14)
HANDS = hand(54, 62, 300, 6) + " " + hand(54, 62, 60, 10)

# (kind, path, colour or None for "cut out" in the page's teal, stroke width)
FULL = [
    ("fill", BODY, WHITE),
    ("fill", HEADER, LIGHT_TEAL),
    ("fill", RINGS, WHITE),
    ("stroke", DIAL, TEAL, 3.5),
    ("stroke", HANDS, TEAL, 3.5),
]
# Themed icons are one colour, tinted by the system, so the monochrome
# layer is the same drawing as outlines.
MONO = [
    ("stroke", rounded_rect(28.5, 29.5, 51, 51, 9), "#000000", 4),
    ("stroke", "M29,42 H79", "#000000", 4),
    ("fill", RINGS, "#000000"),
    ("stroke", DIAL, "#000000", 3.5),
    ("stroke", HANDS, "#000000", 3.5),
]


def svg(shapes, view_box="0 0 108 108", background=None, corner=None):
    x, y, w, h = (float(v) for v in view_box.split())
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view_box}">']
    if corner is not None:
        parts.append(
            f'<clipPath id="c"><rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{corner}"/></clipPath><g clip-path="url(#c)">'
        )
    if background:
        parts.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="{background}"/>')
    for kind, d, colour, *width in shapes:
        if kind == "fill":
            parts.append(f'<path d="{d}" fill="{colour}"/>')
        else:
            parts.append(
                f'<path d="{d}" fill="none" stroke="{colour}" stroke-width="{width[0]}" '
                'stroke-linecap="round" stroke-linejoin="round"/>'
            )
    if corner is not None:
        parts.append("</g>")
    parts.append("</svg>")
    return "".join(parts)


def vector_drawable(shapes, comment):
    parts = [
        '<?xml version="1.0" encoding="utf-8"?>',
        f"<!-- {comment} Generated by tool/icon/generate.py. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp"',
        '    android:height="108dp"',
        '    android:viewportWidth="108"',
        '    android:viewportHeight="108">',
    ]
    for kind, d, colour, *width in shapes:
        argb = "#FF" + colour.lstrip("#").upper()
        if kind == "fill":
            parts.append(f'    <path\n        android:fillColor="{argb}"\n        android:pathData="{d}" />')
        else:
            parts.append(
                f'    <path\n        android:pathData="{d}"\n'
                f'        android:strokeColor="{argb}"\n        android:strokeWidth="{width[0]}"\n'
                '        android:strokeLineCap="round"\n        android:strokeLineJoin="round" />'
            )
    parts.append("</vector>")
    return "\n".join(parts) + "\n"


def write(path, text):
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as f:
        f.write(text)


def main():
    # What a launcher shows: the middle 72x72, as a rounded square.
    visible = svg(FULL, "18 18 72 72", background=TEAL, corner=16)
    # Maskable (web): the whole canvas, which platforms crop to a shape.
    full_bleed = svg(FULL, background=TEAL)

    write("tool/icon/app_icon.svg", full_bleed + "\n")
    write("tool/icon/app_icon_monochrome.svg", svg(MONO) + "\n")
    res = "android/app/src/main/res"
    write(f"{res}/drawable/ic_launcher_foreground.xml",
          vector_drawable(FULL, "The launcher icon's foreground: a calendar page whose body is a clock."))
    write(f"{res}/drawable/ic_launcher_monochrome.xml",
          vector_drawable(MONO, "The launcher icon for themed icons (Android 13+): the same drawing in outline."))

    with sync_playwright() as p:
        browser = p.chromium.launch(executable_path=os.environ.get("CHROMIUM"))
        page = browser.new_page()

        def render(markup, size):
            sized = markup.replace("<svg ", f'<svg width="{size}" height="{size}" ', 1)
            page.set_viewport_size({"width": size, "height": size})
            page.set_content(
                '<html><body style="margin:0;background:transparent">'
                f'<div style="width:{size}px;height:{size}px">{sized}</div>'
                "</body></html>"
            )
            return Image.open(io.BytesIO(page.screenshot(omit_background=True))).convert("RGBA")

        def save_png(markup, size, path):
            render(markup, size).save(os.path.join(ROOT, path), optimize=True)

        for density, size in [("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)]:
            save_png(visible, size, f"{res}/mipmap-{density}/ic_launcher.png")
        save_png(visible, 32, "web/favicon.png")
        save_png(visible, 192, "web/icons/Icon-192.png")
        save_png(visible, 512, "web/icons/Icon-512.png")
        save_png(full_bleed, 192, "web/icons/Icon-maskable-192.png")
        save_png(full_bleed, 512, "web/icons/Icon-maskable-512.png")

        sizes = [16, 20, 24, 32, 40, 48, 64, 128, 256]
        big = render(visible, 256)
        big.save(
            os.path.join(ROOT, "windows/runner/resources/app_icon.ico"),
            format="ICO",
            sizes=[(s, s) for s in sizes],
            append_images=[render(visible, s) for s in sizes[:-1]],
        )
        browser.close()


if __name__ == "__main__":
    sys.exit(main())
